import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

import {
  parseJsonc,
  replaceJsoncStringMember,
  stripJsoncComments,
  stripJsoncTrailingCommas,
} from "../scripts/lib/jsonc.mjs";

const COMMENTED_CONFIG = `{
  // The deployed Worker name.
  "name": "personal-site-game-stats",
  /* The browser build this Worker accepts.
     Generated by scripts/update-game-integrity.mjs. */
  "vars": {
    "ALLOWED_ORIGIN": "https://rohin.shanker.me", // Production origin only.
    "GAME_BUILD_VERSION": "sha256-${"a".repeat(64)}",
    "GAME_BUILD_COMPATIBILITY_VERSIONS": "",
  },
  "secrets": { "required": ["EVENT_SIGNING_SECRET"] },
}`;

test("a JSONC reader parses line comments, block comments, and trailing commas", () => {
  assert.deepEqual(parseJsonc(COMMENTED_CONFIG), {
    name: "personal-site-game-stats",
    vars: {
      ALLOWED_ORIGIN: "https://rohin.shanker.me",
      GAME_BUILD_VERSION: `sha256-${"a".repeat(64)}`,
      GAME_BUILD_COMPATIBILITY_VERSIONS: "",
    },
    secrets: { required: ["EVENT_SIGNING_SECRET"] },
  });
});

test("comment stripping keeps string contents, offsets, and line numbers", () => {
  const source = '{"url": "https://example.test/a//b", "n": 1 /* tail */}';
  const stripped = stripJsoncComments(source);

  assert.equal(stripped.length, source.length);
  assert.match(stripped, /"https:\/\/example\.test\/a\/\/b"/);
  assert.doesNotMatch(stripped, /tail/);
  assert.deepEqual(parseJsonc(source), { url: "https://example.test/a//b", n: 1 });
  assert.equal(
    stripJsoncComments('{\n// first\n"a": 1\n}').split("\n").length,
    4
  );
  const unterminatedBlock = '{"a": 1} /* unterminated';
  assert.equal(
    stripJsoncComments(unterminatedBlock),
    `{"a": 1}${" ".repeat(unterminatedBlock.length - 8)}`
  );
  assert.equal(stripJsoncComments('{"a": "\\"//\\""}'), '{"a": "\\"//\\""}');
  assert.equal(stripJsoncComments('{"a": "unterminated'), '{"a": "unterminated');
});

test("trailing-comma stripping ignores commas inside strings and nested closers", () => {
  assert.equal(stripJsoncTrailingCommas('{"a": "x,y"}'), '{"a": "x,y"}');
  assert.deepEqual(parseJsonc('[[1, 2,], {"a": 1,},]'), [[1, 2], { a: 1 }]);
  assert.deepEqual(parseJsonc('{"a": [1, 2]}'), { a: [1, 2] });
});

test("a JSONC reader rejects a non-string source", () => {
  assert.throws(() => parseJsonc(null), TypeError);
});

test("rewriting a build member preserves every comment around it", () => {
  const nextBuildVersion = `sha256-${"b".repeat(64)}`;
  const updated = replaceJsoncStringMember(
    COMMENTED_CONFIG,
    "GAME_BUILD_VERSION",
    nextBuildVersion
  );

  assert.equal(parseJsonc(updated).vars.GAME_BUILD_VERSION, nextBuildVersion);
  assert.match(updated, /\/\/ The deployed Worker name\./);
  assert.match(updated, /\/\* The browser build this Worker accepts\./);
  assert.match(updated, /\/\/ Production origin only\./);
  assert.equal(
    updated.replace(nextBuildVersion, "a".repeat(64).replace(/^/, "sha256-")),
    COMMENTED_CONFIG
  );
});

test("rewriting rejects a member that is absent or ambiguous", () => {
  assert.throws(
    () => replaceJsoncStringMember(COMMENTED_CONFIG, "MISSING_MEMBER", "value"),
    /exactly one string member named MISSING_MEMBER/
  );
  assert.throws(
    () =>
      replaceJsoncStringMember(
        '{"a": {"same": "1"}, "b": {"same": "2"}}',
        "same",
        "3"
      ),
    /exactly one string member named same/
  );
});

test("the checked-in Wrangler configurations parse through the shared reader", async () => {
  for (const relativePath of [
    "../workers/game-stats/wrangler.jsonc",
    "../workers/game-stats/wrangler.jsonc.example",
  ]) {
    const config = parseJsonc(
      await readFile(new URL(relativePath, import.meta.url), "utf8")
    );
    assert.equal(config.name, "personal-site-game-stats");
    assert.match(config.vars.GAME_BUILD_VERSION, /^sha256-[a-f0-9]{64}$/);
  }
});
